source 'https://rubygems.org'

ruby '>= 3.0.0'

gem 'sinatra', '~> 3.1'
gem 'puma', '~> 6.4'
gem 'rack', '~> 2.2'
gem 'json', '~> 2.7'
gem 'httparty', '~> 0.21'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.0'
  gem 'rubocop', '~> 1.59'
end
